### ISSUE TITLE
Link to IPNS is broken

### ISSUE THREAD

**Issue by bronger** [ipfs/specs#113]
In the top-level `README.md`, the link to the IPNS is broken.

**Comment by RichardLitt** [comment]
Technically, it is - but that's because there is currently no real discussion grounds for IPNS. It exists in @jbenet's head, in a few issues, and in the whitepaper. 

I think that IPNS should have it's own section, maybe - perhaps a repo, perhaps a folder in this repo. I have a note to remind myself to "Split up IPNS", but I don't recall what this means. 

@jbenet Do you know?

**Comment by RichardLitt** [comment]
I removed the link, for now. We can re-add it when we consolidate.
