### ISSUE TITLE
Formal Language for Specs

### ISSUE THREAD

**Issue by dgrisham** [ipfs/specs#169]
## Background

I've been looking through the current [Bitswap spec](https://github.com/ipfs/specs/tree/master/bitswap) and preparing to update it. When I got to the description of the [wire format](https://github.com/ipfs/specs/tree/master/bitswap#wire-format), I was a bit confused by the provided protobuf:

```
message Message {
  message Wantlist {
    message Entry {
      optional string block = 1; // the block key
      optional int32 priority = 2; // the priority (normalized). default to 1
      optional bool cancel = 3;  // whether this revokes an entry
    }

    repeated Entry entries = 1; // a list of wantlist entries
    optional bool full = 2;     // whether this is the full wantlist. default to false
  }

  optional Wantlist wantlist = 1;
  repeated bytes blocks = 2;
}
```

One of the primary confusions I had was with the apparent overuse of the `optional` keyword. When I asked about this, @stebalien told me that it was recommended to use `optional` on all fields in a protobuf. The issue here, though, is that the specification shouldn't consider implementation details such as this when describing the general format of messages/types/functions/etc.

Upon a (very brief) look around the specs repo, it seems as though the specifications use (at least) Go, Javascript, protobufs, and english as languages to help describe various types/interfaces for IPFS/libp2p.

## Proposal

My proposal is that we choose a language with an expressive type system and start moving our specifications to use that language wherever possible. This would have a few benefits:

1. Readability
2. Consistency among specs and reduced ambiguity
3. Expressiveness -- Neither Go nor Javascript have very expressive type systems, and protobufs come with implementation details that shouldn't be necessary.
4. Formal verification -- There are languages like [K](http://www.kframework.org/index.php/Main_Page) that can be great for writing executable specifications for automated proofs that are based on the formal semantics we specify. For example, we could use K to express the formal semantics of Bitswap and use it to prove that Bitswap will never enter a certain set of states, or that some subset of states will always be reached, etc. While we may not immediately use K or a related tool, we should start our trajectory in that direction.

One option to start us off in a good direction would be Haskell -- a first-pass rewrite of the Bitswap wire format protobuf above could be:

``` haskell
data BitswapMessage = Message (Maybe Wantlist) [Block]

data Wantlist = Wantlist [Entry] IsComplete

data Entry = Entry CID Priority Cancel
type IsComplete = Bool
type CID = String
type Priority = Int32
```

**Aside on Haskell types/syntax**

The `data` keyword specifies a new data type on the left-hand side, and on the right-hand side is a list of data constructors. For example, `data Color = RGB Byte Byte Byte | Greyscale Float` declares a data type `Color` with two constructors: `RGB`, which has 3 `Byte` arguments (the red, blue, and green intensities), and `Greyscale`, which has a single argument (a `Float` between 0 and 1). The `type` keyword, on the other hand, declares a type synonym: so we could update our `Color` data type by declaring type synonyms `type Red = Byte`, `type Blue = Byte`, and `type Green = Byte`, then rewrite our data declaration as `data Color = RGB Red Green Blue`.

Regarding the wire format, the first line says that a `BitswapMessage` *might* contain a `Wantlist` (hence the `Maybe Wantlist`), as well as a (potentially empty) list of blocks (`[Block]`). A `Wantlist` contains a list of entries (`[Entry]`) as well as a `Bool` indicating whether the `Wantlist` is complete or not (hence the `IsComplete` field, which is a synonym for `Bool`).

**Note on Haskell's type system**

We may want to express value restrictions in types as well, e.g. in the `Greyscale Float` constructor example above, it would be nice to use the type to indicate that the `Float` must be between 0 and 1 -- e.g. with a type called `NormalizedFloat` or `UnitInterval`. While we can't enforce this via the type system, we can use descriptive names and helper functions + smart tests to handle cases like this (if we were to want to expand our use of Haskell outside of purely type-based specs).

## Thoughts?

For writing formal specifications, we should choose an expressive yet formal language that can clearly communicate types/interfaces that we want to define. This would provide a clear and consistent means of specifying various pieces of projects, as well as giving a strong basis for formal testing that we may want to do.

Haskell can be very readable for this purpose and is less esoteric than other options, however it would make sense to start moving to something like K in the long run once we have a better idea of what makes sense for our purposes.

Right now, I'm proposing that we start moving to Haskell for implementation-agnostic specs, i.e. things that would be implemented in Go, Javascript, etc. but can be separately specified in a formal manner. Maybe there's a better approach/language for this, let me know your thoughts!

pinging @diasdavid @jbenet @whyrusleeping @lgierth @VictorBjelkholm @dignifiedquire @stebalien

**Comment by whyrusleeping** [comment]
👎 to using haskell types. Any type language that we use to describe our specs should be easily understood by any average reader. This is why we use type definitions in go, and in protobuf. they are both relatively simple type systems that don't impose excess cognitive load on the user.  This is your point 1, Readability.

**Comment by Stebalien** [comment]
>  The issue here, though, is that the specification shouldn't consider implementation details such as this when describing the general format of messages/types/functions/etc.

At the end of the day, these fields *are* optional. That is, the receiver should be able to handle any missing or unknown fields (even if that means dropping the message).

Also, in this case, the use of protobuf is literally part of the spec so we should definitely keep it. Honestly, I don't see any point in including any other descriptions: an implementer will need to read the protocol buffer documentation to implement/understand the spec.

---

In more general cases, I'd shy away from Haskell because 99.9% of our contributors will have almost no experience with the language and the type syntax is about as obscure as it gets to anyone but a mathematician.

---

As for go versus javascript: that depends. If we're exchanging JSON blobs, we'll use JSON syntax. If we're describing an *interface*, we'll use the language in which that interface is implemented.

The tricky part comes when we're describing a "general purpose" interface. In that case, we can't really pick a language because the "best" interface will depend on the language. In this case, we should probably just describe the general interface in english:

> # Function: myFunction
> **Inputs:**
> * y: ...
> * z: ...
> **Outputs:**
> * z: ...
> **Errors:**
> * Failed to open file...
>
> Description of function.

**Comment by dgrisham** [comment]
So I think I made a mistake in the OP by conflating the ideas of 'readable documents for contributors/etc.' and 'unambiguous and testable formal specification'. What I'm going for here is the latter: an unambiguous formal spec that can be reasoned about, programmatically or otherwise. This is why I'm suggesting Haskell as a starting point, and a better tool (e.g. K) in the future. The Haskell's type system and purity+immutability-by-default leave far less room for ambiguity than Go's or Javascript's, and is thus a much better starting point if we want to approach the use of formal verification tools.

As far as where the 'readable documents for contributes/etc.' lie in relation to that, I'm not exactly sure. Maybe we have both descriptions ('readable' + 'formal') to improve accessibility and documentation. Or maybe the relevant repositories (e.g. `go-ipfs-bitswap` (which doesn't exist yet, of course), `js-ipfs-bitswap`, etc.) host their own descriptions for contributors, which would keep the language-specific details alongside their respective repositories. In the latter case, maybe @Stebalien's suggestion of english-language interfaces make the most sense for the actual documentation.

In fact, that may not be a bad path to go on. One way to handle this would be to have a formal spec where the unambiguous definitions in Haskell/K/whatever are surrounded by english-language descriptions of what the formal spec is defining. We could then automatically extract out the code into source files that we run to perform proofs, and also automatically extract the english-language descriptions for contributors (who, as you've both noted, probably don't want to read Haskell code). To get an idea of what I mean, check out the [repo for the K EVM project](https://github.com/kframework/evm-semantics). All of their `K` code is embedded in their `.md` files that describe the `K` code, and they use [`pandoc-tangle`](https://github.com/ehildenb/pandoc-tangle) to separate out the code to create the actual `*.k` files (which helps ensure everything is consistent/up-to-date while also providing readable documentation for the `K` code).

**Comment by Stebalien** [comment]
Just to make sure we're on the same page:

1. Any solution that mandates keeping two forms of documentation in sync is a non-starter: they *will not* be kept in sync.
2. Any solution that requires contributors to read or write Haskell, K, Coq, or custom extractors is a non-starter: our contributors won't touch it.

---

I agree that what the K EVM project is doing is the right approach. However, you may notice that that's *not* the spec for the EVM. It's just a formal spec/model for proofs which is allowed to lag behind the main spec.

If we were to build formal definitions + proofs into all of our specs:

* Spec contributors would have to learn the formal definition/proof systems.
* We'd have to actually formally define every new piece of a spec before accepting it.

While we'd love to eventually have our set-in-stone specs formally defined and proved forcing ourselves to do this along the way would likely just stop us from ever actually writing up any specs due to time constraints/disinterest.

---

Note: My point about "english" documentation was specifically referring to APIs that ipfs, ipld, and libp2p libraries should implement: these are more guidelines for consistency than anything else. There would be no formal specs.

---

Note: There *is* a protobuf to Haskell extractor that will write Haskell type definitions from `.proto` files.

**Comment by dgrisham** [comment]
@Stebalien @whyrusleeping I see where you're both coming from, let's postpone discussion on this topic for the time being. Also, side note as a point of interest, I believe KEVM is actually leading the EVM yellow paper.
