### ISSUE TITLE
Use the .onion TLD

### ISSUE THREAD

**Issue by gjvnq** [ipfs/specs#228]
I think adopting ```*.ipfs.onion``` and ```*.ipns.onion``` would be a good way to improve usability.

Some advantages:

  * ```.onion``` is already reserved, so there is no need to ask IETF and IANA for new TLDs.
  * In my understanding of TOR, short names don't happen, so ```*.ipfs.onion``` and ```*.ipns.onion``` would not lead to conflict.

Also, I think subdomains by hash (like ```Qm...mfB.ipfs.onion/index.html```) is better than a path (like ```ipfs.dweb/ipfs/Qm...mfB/index.html```) because it separates Cookies, LocalStorage and other things, thus improving privacy and reducing chances of name conflicts and bugs.

**Comment by Stebalien** [comment]
`.onion` is reserved for TOR addresses so we can't do that.

However, we do own `dweb.link` and plan on using `HASH.{ipfs,ipns,ipld}.dweb.link` as the "default" gateway in the future.

See: https://bafybeigdj3c7jc6hqyzm62ly4dn75fesosu47lyr2iikf2onmhr3grl4ou.ipfs.dweb.link/

(note: we need to use base32 instead of base58 as domains are case-insensitive)

**Comment by gjvnq** [comment]
Cool!

Thanks
