### ISSUE TITLE
Serving dynamic content via IPFS

### ISSUE THREAD

**Issue by polkovnikov-ph** [ipfs/specs#28]
- Where could I read on implementing something inherently dynamic like a chat in IPFS?
 - Should every message modify an IPNS entry to the latest message in a linked list of blocks?
 - Should there be an authority that owns an IPNS entry to keep a chat working? There could be a set of authorities that should simultaneously accept new entry otherwise, but I couldn't find how IPFS is implemented, so I'm unsure if this is possible currently.

Such example would be nice to have to understand the proper way to develop for IPFS networks and it would serve like a proof that dynamic content _is_ servable over IPFS.

**Comment by jbenet** [comment]
@krl has some nice ideas around datastructures for a blog.

the matrix.org people use a dag of updates that's similar to what you'd want to do in ipfs.

> Should every message modify an IPNS entry to the latest message in a linked list of blocks?

i would do it with each sender maintaining their own head at their own ipns entry. and they link to all messages they have seen previously as well. so you'd have a log of "seen" messages

> Should there be an authority that owns an IPNS entry to keep a chat working? There could be a set of authorities that should simultaneously accept new entry otherwise, but I couldn't find how IPFS is implemented, so I'm unsure if this is possible currently.

one channel authority is certainly the easiest way, but i'd try to get it working without. 

I'll give some thought to the datastructure and post a design back here. i think other people have made merkleized chats before though so worth looking around too

**Comment by diasdavid** [comment]
Hey! It has been a while since an update on this thread, @haadcode and @noffle have been developing applications that can give you a good sense of how dynamic content can work on top of IPFS, for e.g: https://github.com/haadcode/orbit

Other sources of info are:

- https://github.com/ipfs/notes/issues/90
- https://github.com/ipfs/notes/issues/66

Let me know if it is helpful. For more questions, consider consulting the [FAQ](http://github.com/ipfs/faq) repo or opening a new issue there, this repo is reserved for specs itself.
